import 'dart:async';
import 'package:covidapiglob/src/models/casoDetails_model.dart';
import 'package:covidapiglob/src/models/respuesta_model.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class Covid19Provider {
  String _URL = 'covid19.mathdro.id';


  Future<Respuesta> getRespuesta() async {
    //Construye la URI a partir de la URL del sitio y la de la peticion
    //https://covid19.mathdro.id/api
    final url = Uri.https(_URL, '/api', {
      
    });
    //Espera a que se complete la solicitud http
    return await _proccessResp(url);
  }

  Future<Respuesta> _proccessResp(Uri url) async {
    final resp = await http.get(url);
    final decodeData = json.decode(resp.body);

    final respuesta = new Respuesta.fromJSON_Map(decodeData);

    return respuesta;
  }

  Future<List<CasoDetailsCountry>> getCountriesByCaso(String caso) async {

    //Construye la URI a partir de la URL del sitio y la de la peticion
    //3/movie/popular?api_key=<<api_key>>&language=en-US&page=1
    final url = Uri.https(_URL, '/api/$caso', {
  
    });
    final resp = await http.get(url);
    final decodeData = json.decode(resp.body);
print(decodeData.length);
print(decodeData.runtimeType);
    final respuesta = new Countries.fromJSON_List(decodeData);

    return respuesta.paises;
  }

}// Generated by https://quicktype.io

